export enum API {
  USERS = "/api/users",
  USER = "/api/users/:id",
  USER_REGISTER = "/api/users/register",
  USER_LOGIN = "/api/users/login",
  USER_GET_CURRENT = "/api/users/current",
  USER_LOGOUT = "/api/users/logout",
  MAIN_CAROUSEL_GET = "api/carousel",
  MAIN_CAROUSEL_UPLOAD = "api/carousel/upload",
  BANNER_GET = "api/banner",
  BANNER_UPLOAD = "api/banner/upload",
  PRODUCTS_GET = "api/products",
  PRODUCT_GET = "api/products/",
  PRODUCTS_BY_CATEGORY_GET = "api/products/by_category/",
  PRODUCT_UPLOAD = "api/products/create",
}
